-- Auto-generated by src/scripts/generateHasuraSeed.ts

BEGIN;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  1,
  'Essence Mascara Lash Princess',
  'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  9.99,
  'beauty',
  'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp"}'::text[],
  2.56,
  99,
  'Essence'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  2,
  'Eyeshadow Palette with Mirror',
  'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.',
  19.99,
  'beauty',
  'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp"}'::text[],
  2.86,
  34,
  'Glamour Beauty'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  3,
  'Powder Canister',
  'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  14.99,
  'beauty',
  'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp"}'::text[],
  4.64,
  89,
  'Velvet Touch'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  4,
  'Red Lipstick',
  'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  12.99,
  'beauty',
  'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp"}'::text[],
  4.36,
  91,
  'Chic Cosmetics'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  5,
  'Red Nail Polish',
  'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  8.99,
  'beauty',
  'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp"}'::text[],
  4.32,
  79,
  'Nail Couture'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  11,
  'Annibale Colombo Bed',
  'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
  1899.99,
  'furniture',
  'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp"}'::text[],
  4.77,
  88,
  'Annibale Colombo'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  12,
  'Annibale Colombo Sofa',
  'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
  2499.99,
  'furniture',
  'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp"}'::text[],
  3.92,
  60,
  'Annibale Colombo'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  13,
  'Bedside Table African Cherry',
  'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
  299.99,
  'furniture',
  'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp","https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp","https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp"}'::text[],
  2.87,
  64,
  'Furniture Co.'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  14,
  'Knoll Saarinen Executive Conference Chair',
  'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
  499.99,
  'furniture',
  'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp","https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp","https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp"}'::text[],
  4.88,
  26,
  'Knoll'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  15,
  'Wooden Bathroom Sink With Mirror',
  'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
  799.99,
  'furniture',
  'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp","https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp","https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp"}'::text[],
  3.59,
  7,
  'Bath Trends'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  16,
  'Apple',
  'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.',
  1.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/apple/1.webp"}'::text[],
  4.19,
  8,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  17,
  'Beef Steak',
  'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.',
  12.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp"}'::text[],
  4.47,
  86,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  18,
  'Cat Food',
  'Nutritious cat food formulated to meet the dietary needs of your feline friend.',
  8.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp"}'::text[],
  3.13,
  46,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  19,
  'Chicken Meat',
  'Fresh and tender chicken meat, suitable for various culinary preparations.',
  9.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp","https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp"}'::text[],
  3.19,
  97,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  20,
  'Cooking Oil',
  'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.',
  4.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp"}'::text[],
  4.8,
  10,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  21,
  'Cucumber',
  'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.',
  1.49,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp"}'::text[],
  4.07,
  84,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  22,
  'Dog Food',
  'Specially formulated dog food designed to provide essential nutrients for your canine companion.',
  10.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp"}'::text[],
  4.55,
  71,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  23,
  'Eggs',
  'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.',
  2.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp"}'::text[],
  2.53,
  9,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  24,
  'Fish Steak',
  'Quality fish steak, suitable for grilling, baking, or pan-searing.',
  14.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp"}'::text[],
  3.78,
  74,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  25,
  'Green Bell Pepper',
  'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.',
  1.29,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp"}'::text[],
  3.25,
  33,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  26,
  'Green Chili Pepper',
  'Spicy green chili pepper, ideal for adding heat to your favorite recipes.',
  0.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp"}'::text[],
  3.66,
  3,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  27,
  'Honey Jar',
  'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.',
  6.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp"}'::text[],
  3.97,
  34,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  28,
  'Ice Cream',
  'Creamy and delicious ice cream, available in various flavors for a delightful treat.',
  5.49,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp","https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp","https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp","https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp"}'::text[],
  3.39,
  27,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  29,
  'Juice',
  'Refreshing fruit juice, packed with vitamins and great for staying hydrated.',
  3.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/juice/1.webp"}'::text[],
  3.94,
  50,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  30,
  'Kiwi',
  'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.',
  2.49,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp"}'::text[],
  4.93,
  99,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  31,
  'Lemon',
  'Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.',
  0.79,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/lemon/1.webp"}'::text[],
  3.53,
  31,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  32,
  'Milk',
  'Fresh and nutritious milk, a staple for various recipes and daily consumption.',
  3.49,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/milk/1.webp"}'::text[],
  2.61,
  27,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  33,
  'Mulberry',
  'Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.',
  4.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/mulberry/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/mulberry/1.webp"}'::text[],
  4.95,
  99,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  34,
  'Nescafe Coffee',
  'Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.',
  7.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/1.webp"}'::text[],
  4.82,
  57,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  35,
  'Potatoes',
  'Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.',
  2.29,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/potatoes/1.webp"}'::text[],
  4.81,
  13,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  36,
  'Protein Powder',
  'Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.',
  19.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/protein-powder/1.webp"}'::text[],
  4.18,
  80,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  37,
  'Red Onions',
  'Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.',
  1.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/red-onions/1.webp"}'::text[],
  4.2,
  82,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  38,
  'Rice',
  'High-quality rice, a staple for various cuisines and a versatile base for many dishes.',
  5.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/rice/1.webp"}'::text[],
  3.18,
  59,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  39,
  'Soft Drinks',
  'Assorted soft drinks in various flavors, perfect for refreshing beverages.',
  1.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/soft-drinks/1.webp"}'::text[],
  4.75,
  53,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  40,
  'Strawberry',
  'Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.',
  3.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/strawberry/1.webp"}'::text[],
  3.08,
  46,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  41,
  'Tissue Paper Box',
  'Convenient tissue paper box for everyday use, providing soft and absorbent tissues.',
  2.49,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/1.webp","https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/2.webp"}'::text[],
  2.69,
  86,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  42,
  'Water',
  'Pure and refreshing bottled water, essential for staying hydrated throughout the day.',
  0.99,
  'groceries',
  'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/groceries/water/1.webp"}'::text[],
  4.96,
  53,
  'Unknown'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  6,
  'Calvin Klein CK One',
  'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.',
  49.99,
  'fragrances',
  'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp"}'::text[],
  4.37,
  29,
  'Calvin Klein'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  7,
  'Chanel Coco Noir Eau De',
  'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
  129.99,
  'fragrances',
  'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp"}'::text[],
  4.26,
  58,
  'Chanel'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  8,
  'Dior J''adore',
  'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.',
  89.99,
  'fragrances',
  'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/3.webp"}'::text[],
  3.8,
  98,
  'Dior'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  9,
  'Dolce Shine Eau de',
  'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.',
  69.99,
  'fragrances',
  'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp"}'::text[],
  3.96,
  4,
  'Dolce & Gabbana'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  10,
  'Gucci Bloom Eau de',
  'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.',
  79.99,
  'fragrances',
  'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp',
  '{"https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp"}'::text[],
  2.74,
  91,
  'Gucci'
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;

COMMIT;

