import "dotenv/config";
import fs from "fs/promises";
import path from "path";

const CATEGORIES = [
  "beauty",
  "furniture",
  "groceries",
  "electronics",
  "fragrances",
  "skincare",
];

interface DummyProduct {
  id: number;
  title: string;
  description: string;
  price: number;
  category: string;
  thumbnail: string;
  images: string[];
  rating: number;
  stock: number;
  brand: string;
}

const SEED_DIR = path.resolve(process.cwd(), "hasura", "seeds", "default");
const SEED_FILE = path.join(SEED_DIR, "products_seed.sql");

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

function sqlText(value?: string | null): string {
  if (!value) return "NULL";
  return `'${sqlEscape(value)}'`;
}

function sqlNumber(value?: number | null): string {
  if (typeof value !== "number" || Number.isNaN(value)) return "0";
  return String(value);
}

function sqlArrayText(values?: string[] | null): string {
  if (!values || values.length === 0) return "'{}'::text[]";
  const escaped = values.map((v) =>
    `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/'/g, "''")}"`
  );
  return `'{${
    escaped.join(",")
  }}'::text[]`;
}

async function fetchCategory(category: string): Promise<DummyProduct[]> {
  const response = await fetch(`https://dummyjson.com/products/category/${category}?limit=100`);
  if (!response.ok) {
    throw new Error(`Failed to fetch category '${category}' (${response.status})`);
  }

  const payload = (await response.json()) as { products?: DummyProduct[] };
  return payload.products ?? [];
}

function buildUpsertStatement(product: DummyProduct): string {
  return `
INSERT INTO products (
  external_id, title, description, price, category, thumbnail, images, rating, stock, brand
) VALUES (
  ${sqlNumber(product.id)},
  ${sqlText(product.title)},
  ${sqlText(product.description)},
  ${sqlNumber(product.price)},
  ${sqlText(product.category)},
  ${sqlText(product.thumbnail)},
  ${sqlArrayText(product.images)},
  ${sqlNumber(product.rating)},
  ${sqlNumber(product.stock)},
  ${sqlText(product.brand ?? "Unknown")}
)
ON CONFLICT (external_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand;`.trim();
}

async function run(): Promise<void> {
  console.log("Generating Hasura seed SQL for products...");

  const allProducts: DummyProduct[] = [];
  for (const category of CATEGORIES) {
    console.log(`- Fetching ${category}`);
    const products = await fetchCategory(category);
    allProducts.push(...products);
  }

  const statements = allProducts.map(buildUpsertStatement);
  const sql = [
    "-- Auto-generated by src/scripts/generateHasuraSeed.ts",
    "BEGIN;",
    ...statements,
    "COMMIT;",
    "",
  ].join("\n\n");

  await fs.mkdir(SEED_DIR, { recursive: true });
  await fs.writeFile(SEED_FILE, sql, "utf8");

  console.log(`Seed file generated: ${SEED_FILE}`);
  console.log(`Rows prepared: ${allProducts.length}`);
}

run().catch((error) => {
  console.error("Failed to generate Hasura seed:", error);
  process.exit(1);
});
